apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-z2yj
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0010-tenant/tkrw-pr712-0075-0010-app/devfile-sample-z2yj@sha256:33f221e082f1de11177a87b4de3ea0f6158b3668a0423b32675a0b860a82bc2b
        name: my-nodejs
        resources: {}
status: {}
